baseURL         = "https://jamespogran.com/"
title           = "James Pogran"
slogan          = "automate all the things"
descripton      = "automate all the things"
languageCode    = "en-us"
googleAnalytics = "UA-74930020-1"
theme = "exlibris"

[permalinks]
  posts = "/:title/"
  talks = "/:title/"

[taxonomies]
  series = "series"
  tags = "tags"

[[menu.main]]
  weight     = 1
  identifier = "post"
  name       = "Blog"
  url        = "/post"

[[menu.main]]
  weight     = 2
  identifier = "book"
  name       = "Books"
  url        = "/book"

[[menu.main]]
  weight     = 3
  identifier = "media"
  name       = "Publications"
  url        = "/media"

[[menu.main]]
  weight     = 0
  identifier = "talk"
  name       = "Talks"
  url        = "/talk"

[params]
  author     = "James Pogran"
  slogan     = "The intersection of Prose and Technology"
  descripton = "automate all the things"
  images     = ["img/learning_powershell_dsc_second_edition.png"]

[params.social]
  facebook      = "full Social profile url in facebook"
  email         = "email@example.com"
  twitter       = "//twitter.com/ender2025"
  linkedin      = "//linkedin.com/in/jamespogran"
  stackoverflow = "//stackoverflow.com/users/1083/james-pogran"
  github        = "//github.com/jpogran"
  rss           = true
