baseURL      = "https://jamespogran.com/"
title        = "James Pogran"
slogan = "automate all the things"
descripton = "automate all the things"
languageCode = "en-us"

[params]
  slogan     = "The intersection of Prose and Technology"
  descripton = "automate all the things"

[params.social]
  facebook      = "full Social profile url in facebook"
  email         = "email@example.com"
  twitter       = "//twitter.com/ender2025"
  linkedin      = "//linkedin.com/user/jamespogran"
  stackoverflow = "//stackoverflow.com/user/1803"
  github        = "//github.com/jpogran"
  rss           = true
