baseURL      = "https://jamespogran.com/"
title        = "James Pogran"
languageCode = "en-us"


[params.social]
  facebook      = "full Social profile url in facebook"
  email         = "email@example.com"
  twitter       = "//twitter.com/ender2025"
  linkedin      = "//linkedin.com/user/jamespogran"
  stackoverflow = "//stackoverflow.com/user/1803"
  github        = "//github.com/jpogran"
  rss           = true
